# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Request a feature
description: Suggest a new feature to include.
title: "[FEATURE] <title>"
labels: [enhancement]
type: Feature
assignees: [exquz3me]
projects: [nlobby4/7]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        Provide detailed information for a feature that should be added, including relevant links whenever possible.

        NOTE: Before submitting, please <a href="https://github.com/nlobby4/{repo}/issues?utf8=%E2%9C%93&q=is%3Aissue">search for duplicate or closed issues</a> and review the <a href="https://github.com/nlobby4/readme-boilerplate/blob/main/.github/CONTRIBUTING.md">contributing guidelines</a>.
    validations:
      required: true
