name: Initialize Repository

on:
  workflow_dispatch:

jobs:
  update-dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run node CLI tool
        run: |
          ./.scripts/index.js

      - name: Commit changes if configuration was updated
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'initialize repository'
          git push
